centos-7:
  script:
    - cd kitchen/centos-7
    - docker login -u gitlab-ci-tocken -p $CI_BUILD_TOKEN registry.ocf.co.uk
    - docker build -t registry.ocf.co.uk/salt/docker/centos-7-kitchen .
    - docker push registry.ocf.co.uk/salt/docker/centos-7-kitchen:latest
  only:
    - master

centos-6:
  script:
    - cd kitchen/centos-6
    - docker login -u gitlab-ci-tocken -p $CI_BUILD_TOKEN registry.ocf.co.uk
    - docker build -t registry.ocf.co.uk/salt/docker/centos-6-kitchen .
    - docker push registry.ocf.co.uk/salt/docker/centos-6-kitchen:latest
  only:
    - master

ubuntu-1604:
  script:
    - cd kitchen/ubuntu-16.04
    - docker login -u gitlab-ci-tocken -p $CI_BUILD_TOKEN registry.ocf.co.uk
    - docker build -t registry.ocf.co.uk/salt/docker/ubuntu-16.04-kitchen .
    - docker push registry.ocf.co.uk/salt/docker/ubuntu-16.04-kitchen:latest
  only:
    - master
